export const Colors = {
  light: {
    text: '#0a1f1e',
    foreground: '#0a1f1e',
    background: '#fbf8f3',
    card: '#ffffff',
    cardForeground: '#0a1f1e',
    primary: '#0d3b3a',
    primaryForeground: '#fbf8f3',
    secondary: '#eee8dc',
    secondaryForeground: '#0a1f1e',
    muted: '#f1ece1',
    mutedForeground: '#6b6457',
    accent: '#f5b962',
    accentForeground: '#0a1f1e',
    destructive: '#c2410c',
    destructiveForeground: '#fbf8f3',
    border: '#e6dfd0',
    input: '#e6dfd0',
    radius: 14,
  },
};
